apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "name" . }}
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
data:
  namespaces.conf: {{ .Values.controlpanel.config.namespaces }}