apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.fabric8.io/update-on-change: "keycloak-proxy"
  labels:
{{ include "labels.stakater" . | indent 4 }}
{{ include "labels.chart" . | indent 4 }}
  name: {{ template "name" . }}
spec:
  replicas: {{ .Values.controlpanel.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.controlpanel.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
{{ include "labels.selector" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "labels.selector" . | indent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: "{{ .Values.controlpanel.image.name }}:{{ .Values.controlpanel.image.tag }}"
        name: {{ template "name" . }}
        volumeMounts:
        - name: {{ template "name" . }}-config
          mountPath: /etc/cp-config
    {{- if .Values.controlpanel.proxy.enabled }}
      - name: proxy
        image: "{{ .Values.controlpanel.proxy.image.name }}:{{ .Values.controlpanel.proxy.image.tag }}"
        args:
        - --config={{ .Values.controlpanel.proxy.args.config }}
        - --upstream-url={{ .Values.controlpanel.proxy.args.upstreamUrl }}
        volumeMounts:
        - name: keycloak-proxy-config
          mountPath: /etc/config
      volumes:
      - name: keycloak-proxy-config
        configMap:
          name: keycloak-proxy
      - name: {{ template "name" . }}-config
        configMap: 
          name: {{ template "name" . }}
    {{- else }}
      volumes:      
      - name: {{ template "name" . }}-config
        configMap: 
          name: {{ template "name" . }}-conf
    {{- end }}
