---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    {{- with .Values.controlpanel.service.annotations }}
    annotations:
      {{- with .ingressPath }}
      fabric8.io/ingress.path: {{ . }}
      {{- end }}
      fabric8.io/ingress.annotations: |-
        {{- with .rewriteTarget }}
        ingress.kubernetes.io/rewrite-target: {{ . }}
        {{- end }}
        {{- with .forceSslRedirect }}
        ingress.kubernetes.io/force-ssl-redirect: {{ . }}
        {{- end }}
        {{- with .ingressClass }}
        kubernetes.io/ingress.class: {{ . }}
        {{- end }}
    {{- end }}
    labels:
{{ include "labels.stakater" . | indent 6 }}
{{ include "labels.chart" . | indent 6 }}
      expose: {{ .Values.controlpanel.service.expose | quote }}
    name: {{ template "name" . }}
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
{{ include "labels.selector" . | indent 6 }}
