controlpanel:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 1.0.1
  namespace: dev
  image:
    name: docker.tools.stackator.com:443/stakater/controlpanel/master
    tag: 1.0.1
  proxy:
    image:
      name: quay.io/gambol99/keycloak-proxy
      tag: v2.1.1
    args:
      config: /etc/config/config.yml
      upstreamUrl: http://100.1.0.0:1234
  service:
    annotations:
      ingressPath: /
      rewriteTarget: /
      forceSslRedirect: "false"
      ingressClass: internal-ingress
    expose: true
